apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiny-http-app.fullname" . }}
  labels:
    {{- include "tiny-http-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "tiny-http-app.selectorLabels" . | nindent 4 }}
